# Generated by Django 2.2.4 on 2019-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('username', models.CharField(max_length=500, verbose_name='Ник')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('followers_count', models.BigIntegerField(verbose_name='Кол-во подписчиков')),
                ('followings_count', models.BigIntegerField(verbose_name='Кол-во подписок')),
                ('posts_count', models.BigIntegerField(verbose_name='Кол-во публикауий')),
                ('man_percent', models.IntegerField(verbose_name='Мужчины %')),
                ('woman_percent', models.IntegerField(verbose_name='Женщины %')),
                ('bots_percent', models.IntegerField(verbose_name='Боты %')),
                ('commerce_accounts_percent', models.IntegerField(verbose_name='Коммерческие аккаунты %')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
